version: '3.8'

services:
  api:
    container_name: api
    image: ${HUB_IMAGE:?Error}
    build:
      context: ./src/
      dockerfile: ./Api/Dockerfile 
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:?Error}
    networks:
      - prometheus-net
    volumes:
      - shared-logs:/app/logs
    restart: always

networks:
  prometheus-net:
    external: true

volumes:
  shared-logs:
    external: true
