name: CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Docker
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify installation

    # Build and run the Docker Compose setup
    - name: Build and run Docker Compose
      run: |
        docker-compose -f ./src/Samarootan.Api/docker-compose.yml up --build -d

    # Run tests inside the container (replace <container_name> with the correct one)
    - name: Run tests
      run: |
        docker exec -t <container_name> dotnet test --no-restore --verbosity normal

    # Stop and remove containers after the tests
    - name: Stop and remove containers
      run: docker-compose -f ./src/Samarootan.Api/docker-compose.yml down
