name: CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify Docker Compose installation

    # Step 4: Build and run the Docker Compose setup (without running the app yet)
    - name: Build Docker Compose (Build only, no test yet)
      run: |
        docker-compose -f ./src/Samarootan.Api/docker-compose.yml build

    # Step 5: Run tests in a dedicated build container (SDK installed)
    - name: Run tests in Docker
      run: |
        docker-compose -f ./src/Samarootan.Api/docker-compose.yml run --rm api dotnet test --no-restore --verbosity normal

    # Step 6: Clean up
    - name: Stop and remove containers after tests
      run: docker-compose -f ./src/Samarootan.Api/docker-compose.yml down
