version: '3.8'

services:
  api:
    container_name: api
    image: ${HUB_IMAGE:?Error}
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:?Error}
    restart: always
