version: '3.8'

services:
  api:
    container_name: dotnet-web-api
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    restart: always
